import runpy


def test_chapter2():
    runpy.run_module("chapter2.chapter2_basics_01")
    runpy.run_module("chapter2.chapter2_basics_02")
    runpy.run_module("chapter2.chapter2_basics_03")
    runpy.run_module("chapter2.chapter2_basics_04")
    runpy.run_module("chapter2.chapter2_basics_05")
    runpy.run_module("chapter2.chapter2_basics_module")
    runpy.run_module("chapter2.chapter2_list_comprehensions_01")
    runpy.run_module("chapter2.chapter2_list_comprehensions_02")
    runpy.run_module("chapter2.chapter2_list_comprehensions_03")
    runpy.run_module("chapter2.chapter2_list_comprehensions_04")
    runpy.run_module("chapter2.chapter2_list_comprehensions_05")
    runpy.run_module("chapter2.chapter2_list_comprehensions_06")
    runpy.run_module("chapter2.chapter2_list_comprehensions_07")
    runpy.run_module("chapter2.chapter2_classes_objects_01")
    runpy.run_module("chapter2.chapter2_classes_objects_02")
    runpy.run_module("chapter2.chapter2_classes_objects_03")
    runpy.run_module("chapter2.chapter2_classes_objects_04")
    runpy.run_module("chapter2.chapter2_classes_objects_05")
    runpy.run_module("chapter2.chapter2_classes_objects_06")
    runpy.run_module("chapter2.chapter2_classes_objects_07")
    runpy.run_module("chapter2.chapter2_classes_objects_08")
    runpy.run_module("chapter2.chapter2_classes_objects_09")
    runpy.run_module("chapter2.chapter2_type_hints_01")
    runpy.run_module("chapter2.chapter2_type_hints_02")
    runpy.run_module("chapter2.chapter2_type_hints_03")
    runpy.run_module("chapter2.chapter2_type_hints_04")
    runpy.run_module("chapter2.chapter2_type_hints_05")
    runpy.run_module("chapter2.chapter2_type_hints_06")
    runpy.run_module("chapter2.chapter2_type_hints_07")
    runpy.run_module("chapter2.chapter2_type_hints_08")
    runpy.run_module("chapter2.chapter2_type_hints_09")
    runpy.run_module("chapter2.chapter2_type_hints_10")
    runpy.run_module("chapter2.chapter2_asyncio_01")
