#!/usr/bin/expect

set send_human {.1 .3 1 .05 2}

set cwd [file dirname $argv0]
set file_path [lindex $argv 0]
set file_name [file tail $file_path]

# Start recording
spawn terminalizer record -c $cwd/config.yml --skip-sharing $file_name
expect "$ "

# Show source code
send -h "pygmentize -g $file_path\r"
sleep 10
send -h "clear\r"

# Execute commands from STDIN
while {[gets stdin command] >= 0} {
  send -h "$command\r"
  sleep 5
}

# Stop recording
send "\x04"
expect "Successfully Recorded"
